### ISSUE TITLE
Emails are using Numbers instead of names

### ISSUE THREAD

**Issue by Drew-Casey** [ecsion/eSeaGrant-Client-Bug-Tracker#1028]
I sent an email through our TXSGReporting@tamu.edu account on Friday that had numbers instead of names. A copy of the email is below. 

From: Reporting TXSG <txsgreporting@tamu.edu> 
Sent: Friday, March 20, 2020 2:33 PM
Subject: Report past due on eSeaGrant
Hello 100402, 
This is just a friendly reminder that your February metrics report is past due. This month has been hectic, so we understand any delays. If you need help with your report or are having any issues, please let us know.
Regards,
TXSGReporting@tamu.edu

**Comment by ecsion** [comment]
Drew, We will need more information to properly troubleshoot this issue. However, most likely the problem is due to using project tags on people module. You can only use project tags when sending emails to selected projects. To troubleshoot further, share the following.
1. Steps you look to send the email.
2. The Template Name & Template Type of the template you selected.

**Comment by Drew-Casey** [comment]
Hello,
1. Steps you look to send the email.
Login to “Reporting TXSG (txsgreporting@tamu.edu<mailto:txsgreporting@tamu.edu>); Went to report call; selected projects from the “Select Projects” in the report dashboard; sent the emails using a template.
2. The Template Name & Template Type of the template you selected.
Email Template - Properties of " Extension Report is Past Due "
Templatename Extension Report is Past Due
Description         Email reminder that report was not completed on time.
Subject Report past due on eSeaGrant
Message
Hello $projects-delegate_pi_name$,

You have a report that is past due on eSeaGrant.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.

**Comment by Drew-Casey** [comment]
I just sent a test email and it did not work.
Steps:

  1.  signed onto TXSGReporting account.
  2.  Went to “EMM-2020-March” report call
  3.  Selected all projects
  4.  Sent email to all PIs and Delegates
  5.  Selected “Report past due on eSeaGrant” email template

All projects got an email with a code instead of a name. Sample below.

Test Email - Please ignore!
Hello 100402,
You have a report that is past due on eSeaGrant.

**Comment by Dipali-Ecsion** [comment]
Apologies, I missed one condition and now i have fixed that as well. Please check now.

**Comment by mzwolinski** [comment]
Hello,

Still no confirmation email received. Thank you for continuing to work on this issue.

Regards,
Mia

Mia Zwolinski
Assistant Director, Research and Fiscal Administration
Texas Sea Grant College Program
Texas A&M University
797 Lamar Street, O&M 306B | 4115 TAMU
College Station, Texas 77843-4115
979-458-0449
mzwolinski@tamu.edu<mailto:mzwolinski@tamu.edu>
http://texasseagrant.org/

**Comment by ecsion** [comment]
Mia, This issue is different. This has to do with tag replacements containing numbers when email is sent to delegates and there is more than 1 delegate. The email issue your e referring to is here: 
https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/issues/1032.

Drew, please check if the number issue is fixed so we can close this.

**Comment by Drew-Casey** [comment]
The email issue looks fixed. I just sent out to a group and their names appeared.
