### ISSUE TITLE
Web site use instructions for the PI

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#124]
After testing the instructions to PI issue, we ran into issues today. The current instructions say, 
“The topics on which we would like you to report and the required documentation of your research work are listed in the sections below. You may navigate through the site either by advancing through the reporting forms in sequence, using the Enter Your Report > link above, or by going directly to a topic section by making a selection in the left-hand Navigation Pane. You must visit each topic in the report and either submit an entry or mark the topic as complete. Topics in the left-hand Navigation Pane marked with a red dot have not been completed. A narrative report is required and must be uploaded.” 

ISSUES:
-We did not see an “Enter Your Report” link.
-Even after we answered all the metrics questions and “submitted,” the red dot wouldn’t go away unless we clicked “Mark Metrics Questions as complete” radio button.
-The topics to report on were not "below", but were in the left side bar.
-We did not require a narrative report. So it was confusing later as the PI was finishing up, they were looking for a place to upload a required narrative.

**Comment by marypleasant** [comment]
Deepak, please upload the following language for site use instructions for Oregon Sea Grant:

Welcome to eSeaGrant. This is where you will share your Oregon Sea Grant project accomplishments, updates, and outcomes. Please report on all sections in the left-hand navigation pane marked with a red dot. You will need to complete the section AND mark each as complete at the top of each section. In order to save your changes, you must click the “save” button at the bottom of each section. You may upload additional documents in the Supplemental Documents section. You will submit your report in the Submission Preview section. 

If you experience technical difficulties, please contact Mary Pleasant (mary.pleasant@oregonstate.edu) or Cathy McBride (cathy.mcbride@oregonstate.edu).

**Comment by mcbridec** [comment]
Wait- we have something to add - Mary has it. : )

**Comment by marypleasant** [comment]
It has been updated. No need to wait on this.

**Comment by ecsion** [comment]
We have added "Web site use instructions" to the instructions on report call. So now you can change it dynamically. However note that you can have only 1 set of site use instructions (i.e. that cannot be changed per report call)

<img width="1171" alt="screen shot 2016-03-28 at 8 11 44 am" src="https://cloud.githubusercontent.com/assets/1612666/14077757/f8fd6114-f4bc-11e5-86b9-231809e6bacc.png">
