### ISSUE TITLE
Resubmitting a reporting task metrics oddity

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#141]
As a PI, I went back into a reporting call task (still open) and updated only one metric, "Tools...". I went to resubmit, it gave me a long list of the things it said I needed to complete. I thought I had to go through and re-"save" all forms so I did that. However, when I tried to resubmit, I got the same incompleted list. While I was wondering what to do next, suddenly my report was submitted!
For a resubmit, should there be no requirement to complete or re-save forms? I think the resubmit is considered final if all the pages/forms are checked as completed at the time the Resubmit button is clicked.
See the picture, odd how the Volunteer hours was repeated.

Here is what is happening: When the PI reports a zero, it is marked incomplete even if there are notes. When the PI doesn't fill in anything or fills in with a value, it is complete. Can we make zeros count as completed field? We want to see the notes on a particular metric even if there are no value assigned to the metric.

![2016-03-25_1520](https://cloud.githubusercontent.com/assets/17169131/14055231/55e30f5e-f29d-11e5-9730-3ae51197c47c.png)

**Comment by ecsion** [comment]
This is because, the current functionality requires the user to manually indicate that the answer is complete. We are taking this approach for the following reason:

#1 Let's say the reporting call requires Student Supported and Partners This Period forms. However, PI does not have Partners This Period. In this case, he will mark Partners This Period as complete even though he did not provided any entries to it.

#2 Let's say he has 5 students supported and he has 3 students entered. Here even though he has some data in Students Supported but it cannot be marked complete till he enters 5 students. Thus we have kept Mark as complete as a manual flag for PI to use as a checklist flag.

**Comment by mcbridec** [comment]
I thought I understood. This only worked fine for the Standard questions and custom forms. Did not work for metrics, and we did re-mark all metrics, forms and questions as complete. Please test as a PI resubmitting metrics on the project #123456. Marking them complete did not work. Marking them with a zero value seemed to be problematic.

**Comment by ecsion** [comment]
fixed. Now only shows sections which  are not marked as completed.
