### ISSUE TITLE
Access to the Proposal from the "Project Information" page

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#206]
Please add a link to download PDF of the "Full Proposal" from the "Project Information" page - put a "Full Proposal" link in the section next to the Project Number, right on the first line.

Like this: 
[Proposal_Dld_Link.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/241099/Proposal_Dld_Link.pdf)

**Comment by mgduke** [comment]
Possibly relevant to this: I thought the full proposal PDF would be under "Project Documents," and indeed that appears to be the case…but the problem is I'm unable to actually download the PDF. Clicking the record takes us to a Project Document edit page, and while the file is listed, it's not a live link (I reported this issue a while ago). I agree that it would be more convenient to have a full-proposal PDF link on the Project Info page. I copy below a link to an example of what I'm talking about:

http://esg.wsg.washington.edu/index.php?module=Projects&relatedModule=OtherDocs&view=Detail&record=1989&mode=showRelatedList&tab_label=Project%20Documents

**Comment by kdez** [comment]
..with the whole system is this “can’t download the PDF” thing. If I, the SGAdmin, can SEE the pdf, I should be able to click and download it – anywhere the link appears.
