### ISSUE TITLE
CASG: URGENT Special Focus Awards: Budget Worksheet Not Updating 

### ISSUE THREAD

**Issue by mumezawa** [ecsion/eSeaGrant-Client-Bug-Tracker#282]
Hi,

The budget worksheet is not updating correctly in the 2017 Special Focus Awards RFP.
When you make updates to the Salaries and Wages, the sum at the bottom "TOTAL SALARIES AND WAGES" is not adding up/updating correctly. 

Cotton Rockwood's proposal is an example of this.
He's currently working on his proposal, but I wanted to give you an example...

http://eseagrant2.ucsd.edu/operations.php?action=budget&proposal_id=MjYzNTg=&id=706&update=1

Thanks,

Miho

**Comment by ecsion** [comment]
Miho -- Please circle the cells that are incorrect and provide correct values.  Otherwise it is hard for us to know where the issues is and what the correct values are.

Attached is the pdf output of the spreadsheet
[Budgetsheet.pdf](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/385234/Budgetsheet.pdf)

**Comment by ecsion** [comment]
Mini, closing this issue. If it is still there, please resubmit a new bug.
