### ISSUE TITLE
Fellowship Instructions Naming Convention

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#437]
I developed a PDF instruction set for a Knauss Fellowship 2018 RFP and uploaded them to eSG. When the applicant downloads the instruction file, the document name is "1995 fellows announcement" [see screen shot]

![screen shot 2016-11-18 at 9 55 43 am](https://cloud.githubusercontent.com/assets/18398763/20434365/78d3cb32-ad75-11e6-84f3-784c92eb97c1.png)

This needs to change to reflect what name of the uploaded file, or to allow the document to be named upon upload by the eSG Administrator.
Thank You.

**Comment by ecsion** [comment]
Alan, please provide url link, this helps us to track to the issue faster.

**Comment by ecsion** [comment]
Alan, The issue here is with the file being uploaded. Pdf viewers frequently show the title metadata coded into the pdf file instead of the name of the file. Here what happened is that you took a pdf file that had the title: "1995 Fellow announcement" and named the file Knauss Fellowship 2018 RFP. Naming the file did not change the metadata stored in the file. Thus either the original file or the downloaded file when opened will continue to say 1995 Dell Announcement. I am closing this issue but call Deepak in case you have questions.
