### ISSUE TITLE
WSG: Showstopper—Aggregating "Suggest Reviewers" Data

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#478]
We created a new form for the PI , "Suggest Reviewers" (see URL or look up in Custom Form). However, a “showstopper” for us is that we need to aggregate data from this form for all proposals in the RFP into an Excel file (e.g., ideally in the RFP Reports section).

If this must wait until r2.0, is there any way in the interim to download this data (e.g., through AWS MySQL admin interface)?

http://esg.wsg.washington.edu/index.php?module=RFPProposal&view=Detail&record=33644&mode=showMultiQuestionStem&QuestionId=33636&tab_label=Suggest%20Reviewers&tab_label=Suggest%20Reviewers
![screen shot 2016-12-02 at 11 02 43 am](https://cloud.githubusercontent.com/assets/17168836/20846523/e81aed54-b87e-11e6-8e03-abb5bab15623.png)

**Comment by mgduke** [comment]
Sorry, I should've been more clear: If we can download the data, great, but we still need some way to connect the suggested reviewer record (row) with its associated proposal. I assume (or hope!) there is a foreign-key ID field in our Suggest Reviewer table that matches the record to the proposal (in another table, presumably), but if the foreign key is just a number, that may not help much. 

If all it takes is knowing which other table to look up to find the ID and presumably corresponding proposal title, great! If not…what might you advise?

**Comment by ecsion** [comment]
noted. We will provide excel output but this will take some time to complete.

**Comment by mgduke** [comment]
Thanks, Deepak: To be clear, we won't need this until some time in February.

**Comment by kdez** [comment]
Now *I* need this at MIT.  I can go to each of the proposals and get the info on suggested peer reviewers, but it is a huge pain.  If I could pop out an Excel list via RFP Reports, it would be a huge help.

**Comment by alandesbonnet** [comment]
I posted this in Basecamp, and as part of the Suggestions for R2 presented to Deepak. Not sure if it was given any thought, but if eSeaGrant is to be fully useful, we really need to have some way of pulling out information for use. I understand the danger of allowing access to database fields—total confusion for many—but for those that can manage that kind of functionality, it would be HUGE. Nuff said….

OUTPUT/EXPORT REPORTS—It would nice to have the option to generate output reports based on what the user, particularly ADMIN, wants or needs to pull out of eSeaGrant. The Custom View creater currently in place in eSeaGrant is helpful, but not very functional overall and does not facilitate export of data or for putting it in report form. For instance, I might want a list of PIs, Proposal Titles, Budget Totals, Graduate Students supported by the project, and Impacts/Accomplishments posted in their Completion Report. I then might want to output those data into Excel/Word/PDF (depending on how nicely formatted they are, or are not) so that I can provide a report to the Dean of the University on Graduate Student Support and Impacts of Sea Grant funded research. The ability to create these kinds of searches, export/output them so the data can be “prettied up,” and the search/report saved for the next time it is needed, would be a great feature to have in eSeaGrant. Expanded reporting options should be applied to reports, people, RFPs, etc. so all data in eSeaGrant are searchable and exportable for customized reporting by individual Sea Grant programs.


Alan Desbonnet
Assistant Director

**Comment by kdez** [comment]
At a certain point, output becomes the name of the game.  The system can be wonderful at collecting data, but if we can’t get it back out in a usable format, collection is a useless exercise.

The ability to generate custom reports  (like in old eSG where you select fields and then export to Excel) would be fabulous, but I fear it would take a tremendous amount of programming…?

K.

**Comment by kdez** [comment]
And now I need to get out all the Objectives, Methodology, Rationale statements for this RFP so I can prepare summaries of each proposal so I can use them to recruit peer reviewers.  In old eSG I could get the PI name, Project Title and these three paragraphs in a text file, et voila.

Again, I can find and copy-and-paste this information in the current system, but it's very laborious.
