### ISSUE TITLE
Labe rename request

### ISSUE THREAD

**Issue by mgduke** [ecsion/eSeaGrant-Client-Bug-Tracker#53]
In People, please rename "eSeaGrant History" to "Proposals and Projects". Those two categories are all we find in checking a number of people, but if other categories can be included, let us know and we'll figure out a different name.

**Comment by mcbridec** [comment]
Oregon Sea Grant is also confused by the term "eSG History" but I assumed it referred to roles because a list of Roles appears for us when one goes to edit or fill in the field. 
However, when sorting by the term, as Marcus says, one gets a list of project reports at least. 
We have not done a lot of testing yet, so not sure if other names are appropriate.

Deepak or Kathy Z, what was the original intent of the field "eSG History"?
