### ISSUE TITLE
OSG: LOR were still accepted by eSG after the deadline passed

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#608]
The application period for our undergraduate fellowship closed last Friday, February 24 at 5:00PM PST. I was under the impression that once this deadline passed, no more applications or letters of recommendation could be submitted. However, there were multiple letters of recommendation that were submitted to the system until 8:00PM on Feb 24, and the system still accepted them.

**Comment by kdez** [comment]
This was designed in as a feature, not a bug - we do not penalize the applicant because their recommenders were late (within reason.)   The same goes for transcripts. Very often these things get delayed through no fault of the student.
But you want the option of a hard cutoff date for the LoRs and transcripts, is that correct?

**Comment by ecsion** [comment]
Can you give us an example of this. Note if you have SGadmin role and your re logged in, there is no check on date and you can go in and submit anytime, even after the phase is closed.

**Comment by epperlyh** [comment]
Yes, we want the option of a hard cutoff time and date for the LORs and transcripts. If that's not possible, then if we could know how long after the deadline those documents will still be accepted by the system that would be great too. 

Deepak - what exactly do you want an example of? I received multiple emails notifying me that letters of recommendation were submitted after the deadline of 5PM. Do you want me to copy those emails?

**Comment by ecsion** [comment]
fixed.
