### ISSUE TITLE
OSG: Some emails do not receive eSG emails

### ISSUE THREAD

**Issue by epperlyh** [ecsion/eSeaGrant-Client-Bug-Tracker#609]
We ran into the problem that some email addresses do not receive any emails from eSG, they don't even go into their spam folder. Here is an example of an email address that was sent a document request from an applicant regarding a letter of recommendation, but the email was never received and was not found in spam tldarcyh@indiana.edu. Here is an example of an email address from an applicant that needed to get set up in the system, but this address did not receive any of the eSG emails, such as the password setting email, katherine.gregory@stonybrook.edu. There have been a few other email addresses, all school email addresses, that seem to block all eSG emails.

**Comment by ecsion** [comment]
Hi Haley, we have a record of email being sent. Ask the user to search the email by subject. See screenshots below
<img width="824" alt="screen shot 2017-03-01 at 9 57 21 am" src="https://cloud.githubusercontent.com/assets/1612666/23465281/c6c4d8d6-fe65-11e6-92da-5ea8f32f0a03.png">
<img width="383" alt="screen shot 2017-03-01 at 9 56 52 am" src="https://cloud.githubusercontent.com/assets/1612666/23465297/d4187e02-fe65-11e6-82f8-015ca8f96c1f.png">

We also found the password email but since it has a password, I am not attaching the screenshot to this ticket.
