### ISSUE TITLE
URGENT Panel Review Scores Not Saving

### ISSUE THREAD

**Issue by marypleasant** [ecsion/eSeaGrant-Client-Bug-Tracker#614]
When a panel reviewers enters a rating for one of our criteria, and then hits "save," the score does not save and making the final panel reviewer score incorrect. This is happening for our RFP: _Oregon Sea Grant SEED Proposal Competition 2018_, specifically for the _Criteria A: Technical/scientific merit: For this competition, assess (1) the technical merits of the research questions posed, including if there are general technical flaws in the proposed methods; (2) the strength and diversity of the interdisciplinary approach, including student training and mentoring; (3) evaluation of success for the SEED project; (4) potential outcomes and feasibility of success for the LEAF project; (5) the originality and innovativeness of the proposal; and (6) how well the proposed works addresses OSG’s research objectives for this opportunity (page 5 of the RFP). Note that detailed methods were not required for SEED proposals. - 35% :_ 

Our review is currently underway with panel reviewers submitting scores now, so fixing this as soon as possible would be most helpful. 
http://eseagrant.oregonstate.edu/operations.php?action=panel_reviewer&guid=Q0VDRTgwMzQtNzJDQy00NzczLUJDQjAtRjgyODk2NjNEODVE&exuti=ODM5OA==

![capture](https://cloud.githubusercontent.com/assets/17168500/23532444/55d7c7ae-ff60-11e6-805d-c49544baa7eb.JPG)

**Comment by ecsion** [comment]
Mary, The issue is use of single quote. Currently eSeagrant is not properly handling single quotes in labels and filenames. we have an update planned for it in a few weeks. Meanwhile, do not use single quotes. We have gone thru all your rating forms and removed the single quote. For example, writing OSG's research objectives creates a problem. Instead write "OSG research objectives" till we have a fix deployed. 

The panel review ratings are now saving properly.

**Comment by marypleasant** [comment]
Great - thank you!
