### ISSUE TITLE
ORSG: Reports- Custom Forms reports, show/hide unanswered questions

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#700]
In Reports, the Custom Form reports results for multi-part questions contain question answers along with rows of blank data showing unanswered sub-questions. This is apparent whenever a PI reports more than one event, etc.. We don’t need to see all the blank fields/questions in those forms reports. The shown PI had 7 different answers and a lot of unanswered sub-questions, making the printed report way too long. 
We use the Excel version of reports to gather activity for PIER, but we pdf the longer version, as shown, for other reading up on PI projects.
Is there a way to choose not to view blank or unanswered sub-questions in Custom Form reports?

For clarification- blank rows in the related Excel export of these forms are fine for now.

![2017-04-28_1539a](https://cloud.githubusercontent.com/assets/17169131/25550014/7a8df202-2c2a-11e7-8ad6-9abce2ff9398.png)

**Comment by ecsion** [comment]
yes it is possible, however, since some programs may want to see blank questions also, we should really allow for both options. 1. Include blank  questions in response PDF output. Skip blank questions in the response PDF output.  We will do this, however, this will take us a few days to do. We will let you know once this is done.

**Comment by mcbridec** [comment]
Sounds good! Thanks
