### ISSUE TITLE
RISG -- IMPORT from Any RFP not available

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#701]
At this URL:

http://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=Edit&record=71&showList=

for RFP Custom Form "CP Support" the IMPORT FROM ANY RFP option is selected (see screen shot)

![screen shot 2017-05-01 at 7 36 12 am](https://cloud.githubusercontent.com/assets/18398763/25578932/2c8f3390-2e41-11e7-9bff-8be1eb26fa02.png)

However, at this URL:  

http://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=8021&mode=showMultiQuestionStem&QuestionId=71&tab_label=CP%20Support&tab_label=CP%20Support

Logged in as a PI, the option to IMPORT the information from any other RFP is not available. Please make the IMPORT option available here so PIs do not have to recreate what they have already done in previous proposals. Thank you.

**Comment by ecsion** [comment]
The reason that the import button is missing even though there is one other  proposal with CP Support question in it is because the other proposal, the user did not enter any response to the CP support question. Here's the link to the other proposal with CP Support question:
http://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=7993&mode=showMultiQuestionStem&QuestionId=71&tab_label=CP%20Support&tab_label=CP%20Support

Notice TestMonkey did not enter any response to CP Support question.

To avoid the confusion, we Can show a Import button always and then we will give a appropriate message as follows:

1. No other proposals found with CP Support question linked to it
2. There are 2 proposals with CP Support questions but either of these proposal has no response attached to CP Support question

Would this work to remove the confusion?

**Comment by alandesbonnet** [comment]
That makes sense. Not being able to log in as the PI makes it difficult to assess what problems they bring to my attention. 

Alan Desbonnet
Assistant Director

**Comment by ecsion** [comment]
The login as PI functionality is slated to be released R2.0 milestone 1.0, planned for end of May.
