### ISSUE TITLE
MIT - Screen is over-writing itself in User Email view

### ISSUE THREAD

**Issue by kdez** [ecsion/eSeaGrant-Client-Bug-Tracker#710]
A screen problem in viewing email templates - this happens consistently:

![image](https://cloud.githubusercontent.com/assets/17729848/25822138/a51db72c-3405-11e7-8f33-9cf95f03a667.png)

**Comment by ecsion** [comment]
Kathy -- please provide url link in the future. It helps us get to the issue faster. In this case we found it:

http://eseagrant.mit.edu/index.php?module=EmailTemplates&view=Detail&record=78&type=Normal

The issue is that you are cutting and pasting html from another source and the css classes are conflicting with css classes in eSeaGrant. To fix this, please use the Copy widget (3rd button on html editor). The last resort would be 4th button (Copy as plain text). 

Let us know if this does not fix the issue.
