### ISSUE TITLE
RISG -- No "< Previous/Next >" options on Document Request Form

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#830]
at this URL:

https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=13625&mode=showMultiQuestionStem&QuestionId=5969&tab_label=Knauss%20Fellowship%20-%20Personal%20Education%20&%20Career%20Goal%20Statement

there is no "< Previous  |  Next >" buttons in the upper right hand corner of the form, as is found in all other forms. This form should also have these buttons so there is consistency for the user throughout all forms. Please add the < Previous  |  Next > buttons to this form. Thank you.

**Comment by ecsion** [comment]
Alan, the issue was the special character & in the "Personal Education & Career Goal Statement". We are no longer adding the title to the url directly. We encrypt it and this will eliminate the special character problem. The new link now is: https://eseagrant.gso.uri.edu/index.php?module=RFPProposal&view=Detail&record=13625&mode=showProposalTitle&tab_label=U3RhcnQgSGVyZQ&tab_label=U3RhcnQgSGVyZQ==
