### ISSUE TITLE
Reopen OSG- forms data #886

### ISSUE THREAD

**Issue by mcbridec** [ecsion/eSeaGrant-Client-Bug-Tracker#887]
Hi- I realize that, but that is not an option in my account. Nor is it an option in a colleagues' account. Something is missing. Attached is what I see when I log in using cathy.mcbride@oregonstate.edu.

![tempsnip](https://user-images.githubusercontent.com/17169131/46972209-e1539300-d072-11e8-99b3-cb128be6f10e.png)

**Comment by ecsion** [comment]
Cathy, The option that you are looking for is one level deeper in the Report call itself. So click the report call of interest and then you will see options to download form data attached to the report call. Earlier we allowed reports from multiple report calls,  however, that was a problem because in some instances the form names were same but the questions changes in 2 different report calls.

**Comment by mcbridec** [comment]
Yes, thank you for replying, but that is not what I hoped  for and need. It is currently useful only if one knows the call title and only wants to pull data only from that particular call. It’s not good for extracting annually reportable data from all calls for a year or to pull data on a regular  basis from all calls. So I am not sure how much this will be used as it is. Certainly not by me, because it is now easier to ask my colleague for a list of all calls within a reporting year date range, then read through  each PI report and manually extract their data.
Unfortunately, the database is not set up for the kind of reporting we do annually, nor for regular ad-hoc reports.
-Cathy

Catherine McBride
Oregon Sea Grant
1600 SW Western Blvd Ste 350
Corvallis OR  97333
541-737-8692
cathy.mcbride@oregonstate.edu<mailto:cathy.mcbride@oregonstate.edu>

**Comment by ecsion** [comment]
Hi Cathy, So understood what you are trying to do. We are investigating restoring the old functionality that will allow you to select forms across report calls. Since the same form name can have different questions in one reporting call to another, we will display answers for each report call in a separate table one below the other. This implementation will take some time. Once we have a better handle at this, we will let you know a eta.

**Comment by mcbridec** [comment]
Thanks so much. Gathering these data for the purpose of analyzing it and reporting out to different entities, primarily for National Sea Grant, almost always requires pulling the PI data out by date that the work was completed, accomplished, or published. Somehow. I understand it may require some thought about how to deal with the differences in forms with the same name.
If you need anything from me, need clarification, or have other questions, just let me know.
-Cathy

**Comment by Dipali-Ecsion** [comment]
Done. Please check.

**Comment by Dipali-Ecsion** [comment]
Fixed. Please check.
![image](https://user-images.githubusercontent.com/17423049/49426638-24a2c600-f7c7-11e8-8ed3-d97755e19ca0.png)

**Comment by mcbridec** [comment]
Thank you - I like that I can now get all of the  custom form reports in one place! The export of files is organized so that each report call is in a tab. Dates that publication are published and duties within projects are completed are critical to reporting correctly to our Federal funder. The Reporting Call name is not a critical issue when reporting. The responses are from all sorts of dates. Can we add a column for date modified by PI?

**Comment by Dipali-Ecsion** [comment]
Done. Please check.
Added PI modified date column in custom form responses excel export.

[CustomFormResponsesExport-12172018.xlsx](https://github.com/ecsion/eSeaGrant-Client-Bug-Tracker/files/2686129/CustomFormResponsesExport-12172018.xlsx)

**Comment by mcbridec** [comment]
Thanks, seems to be fine now.
